// <auto-generated />
using System;
using Erp.Modules.Billing.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Modules.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260704174251_AddInvoicePublicViewToken")]
    partial class AddInvoicePublicViewToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("text");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientNif")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClientViesConsultedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientViesCountryCode")
                        .HasColumnType("text");

                    b.Property<string>("ClientViesName")
                        .HasColumnType("text");

                    b.Property<bool?>("ClientViesValid")
                        .HasColumnType("boolean");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CompanyNif")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IrpfAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IrpfRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("text");

                    b.Property<string>("PublicViewToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RectificationPeriodFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RectificationPeriodTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RectificationReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("RectificationReasonText")
                        .HasColumnType("text");

                    b.Property<Guid?>("RectifiedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SurchargeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifactuHuella")
                        .HasColumnType("text");

                    b.Property<string>("VerifactuQrUrl")
                        .HasColumnType("text");

                    b.Property<bool>("VerifactuRealtimeSubmission")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("VerifactuSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PublicViewToken")
                        .IsUnique();

                    b.HasIndex("RectifiedInvoiceId");

                    b.HasIndex("CompanyId", "Number")
                        .IsUnique();

                    b.ToTable("Invoices", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SurchargeAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SurchargeRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("text");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("text");

                    b.Property<string>("ClientTaxId")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConvertedToInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("GlobalDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GlobalDiscountPct")
                        .HasColumnType("numeric");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentQuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubtotalAfterDisc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubtotalBeforeDisc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxBaseAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceToken")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParentQuoteId");

                    b.HasIndex("CompanyId", "Number")
                        .IsUnique();

                    b.ToTable("Quotes", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.QuoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DiscountPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LineSubtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LineTaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LineTaxBase")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LineTotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteLines", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.QuoteNumberSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year", "Prefix")
                        .IsUnique();

                    b.ToTable("QuoteNumberSeries", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.QuoteStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteStatusHistory", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.VerifactuSubmissionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("boolean");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "InvoiceId");

                    b.ToTable("VerifactuSubmissionLogs", "billing");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Erp.Modules.Billing.Domain.Entities.Invoice", "RectifiedInvoice")
                        .WithMany()
                        .HasForeignKey("RectifiedInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RectifiedInvoice");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("Erp.Modules.Billing.Domain.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.Quote", b =>
                {
                    b.HasOne("Erp.Modules.Billing.Domain.Entities.Quote", "ParentQuote")
                        .WithMany()
                        .HasForeignKey("ParentQuoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentQuote");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.QuoteLine", b =>
                {
                    b.HasOne("Erp.Modules.Billing.Domain.Entities.Quote", "Quote")
                        .WithMany("Lines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.QuoteStatusHistory", b =>
                {
                    b.HasOne("Erp.Modules.Billing.Domain.Entities.Quote", "Quote")
                        .WithMany("StatusHistory")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceLines");
                });

            modelBuilder.Entity("Erp.Modules.Billing.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
