// <auto-generated />
using System;
using Erp.Modules.Treasury.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Modules.Treasury.Infrastructure.Migrations
{
    [DbContext(typeof(TreasuryDbContext))]
    [Migration("20260401000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("treasury")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AccountingAccountCode").HasColumnType("text");
                    b.Property<string>("BIC").HasColumnType("text");
                    b.Property<string>("BankName").IsRequired().HasColumnType("text");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<decimal>("CurrentBalance").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<string>("CurrencyCode").IsRequired().HasDefaultValue("EUR").HasColumnType("text");
                    b.Property<string>("Iban").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<string>("Notes").HasColumnType("text");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId", "Iban").IsUnique();
                    b.ToTable("BankAccounts", "treasury");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.BankMovement", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<Guid>("BankAccountId").HasColumnType("uuid");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("Date").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsReconciled").HasColumnType("boolean");
                    b.Property<Guid?>("MatchedJournalEntryLineId").HasColumnType("uuid");
                    b.Property<string>("Origin").IsRequired().HasDefaultValue("Manual").HasColumnType("text");
                    b.Property<string>("OriginalBankRef").HasColumnType("text");
                    b.Property<Guid?>("ReconciliationBatchId").HasColumnType("uuid");
                    b.Property<string>("Reference").IsRequired().HasColumnType("text");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("BankAccountId");
                    b.HasIndex("ReconciliationBatchId");
                    b.HasIndex("CompanyId", "BankAccountId", "Date");
                    b.ToTable("BankMovements", "treasury");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.CashEffect", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AccountingAccountCode").IsRequired().HasDefaultValue("4310").HasColumnType("text");
                    b.Property<decimal>("Amount").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<Guid?>("BankAccountId").HasColumnType("uuid");
                    b.Property<Guid?>("ClientId").HasColumnType("uuid");
                    b.Property<string>("ClientAccountCode").IsRequired().HasDefaultValue("4300").HasColumnType("text");
                    b.Property<string>("ClientName").IsRequired().HasColumnType("text");
                    b.Property<string>("ClientTaxId").IsRequired().HasColumnType("text");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("DueDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("EffectNumber").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("IssueDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("Notes").HasColumnType("text");
                    b.Property<string>("SEPADownloadUrl").HasColumnType("text");
                    b.Property<string>("SEPAXml").HasColumnType("text");
                    b.Property<string>("Status").IsRequired().HasDefaultValue("Pending").HasColumnType("text");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("BankAccountId");
                    b.HasIndex("CompanyId", "DueDate");
                    b.ToTable("CashEffects", "treasury");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.CashFlowForecast", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<decimal>("ExpectedBalance").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<decimal>("ExpectedInflow").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<decimal>("ExpectedOutflow").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<DateTime>("ForecastDate").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActual").HasColumnType("boolean");
                    b.Property<string>("Notes").HasColumnType("text");
                    b.Property<string>("Source").IsRequired().HasDefaultValue("Manual").HasColumnType("text");
                    b.Property<Guid?>("SourceId").HasColumnType("uuid");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId", "ForecastDate");
                    b.ToTable("CashFlowForecasts", "treasury");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<Guid?>("BankAccountId").HasColumnType("uuid");
                    b.Property<string>("BeneficiaryIban").IsRequired().HasColumnType("text");
                    b.Property<string>("BeneficiaryName").IsRequired().HasColumnType("text");
                    b.Property<string>("BeneficiaryTaxId").IsRequired().HasColumnType("text");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CurrencyCode").IsRequired().HasDefaultValue("EUR").HasColumnType("text");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("ExecutedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("GeneratedBankMovementId").HasColumnType("uuid");
                    b.Property<string>("Notes").HasColumnType("text");
                    b.Property<string>("PaymentType").IsRequired().HasDefaultValue("Supplier").HasColumnType("text");
                    b.Property<DateTime?>("ScheduledDate").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("SourceId").HasColumnType("uuid");
                    b.Property<string>("SourceType").HasColumnType("text");
                    b.Property<string>("Status").IsRequired().HasDefaultValue("Draft").HasColumnType("text");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId", "ScheduledDate");
                    b.ToTable("PaymentOrders", "treasury");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.ReconciliationBatch", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("BankAccountId").HasColumnType("uuid");
                    b.Property<Guid>("CompanyId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("ItemsCount").HasColumnType("integer");
                    b.Property<string>("Notes").HasColumnType("text");
                    b.Property<DateTime>("ReconciledAt").HasColumnType("timestamp with time zone");
                    b.Property<decimal>("TotalAmount").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<string>("Type").IsRequired().HasDefaultValue("Auto").HasColumnType("text");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CompanyId", "BankAccountId", "ReconciledAt");
                    b.ToTable("ReconciliationBatches", "treasury");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.BankMovement", b =>
                {
                    b.HasOne("Erp.Modules.Treasury.Domain.Entities.BankAccount", "BankAccount")
                        .WithMany("BankMovements")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Erp.Modules.Treasury.Domain.Entities.ReconciliationBatch", "ReconciliationBatch")
                        .WithMany("BankMovements")
                        .HasForeignKey("ReconciliationBatchId");
                });

            modelBuilder.Entity("Erp.Modules.Treasury.Domain.Entities.CashEffect", b =>
                {
                    b.HasOne("Erp.Modules.Treasury.Domain.Entities.BankAccount", "BankAccount")
                        .WithMany("CashEffects")
                        .HasForeignKey("BankAccountId");
                });

#pragma warning restore 612, 618
        }
    }
}
