-- ADR-0018 #34 — Piloto Row-Level Security (NO ejecutar en producción sin middleware de sesión)
-- Requiere: SET app.current_tenant = '<company-uuid>' en cada conexión Npgsql antes de queries.
-- Ver: Erp.Infrastructure/Tenancy/ (futuro PostgresTenantSessionInitializer).
--
-- Ejemplo piloto sobre core."Companies" (schema public por defecto en EF migrations):
--
-- ALTER TABLE "Companies" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE "Companies" FORCE ROW LEVEL SECURITY;
--
-- CREATE POLICY companies_tenant_isolation ON "Companies"
--   USING ("Id" = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
--
-- Política de bypass para rol migraciones (solo despliegue):
-- CREATE POLICY companies_migration_bypass ON "Companies"
--   TO erp_migration
--   USING (true);
--
-- Estado jul 2026: script documentado; activación diferida hasta interceptor Npgsql en ErpDbContext.
