// <auto-generated />
using System;
using Erp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Infrastructure.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260405000000_AddFiscalEvents")]
    partial class AddFiscalEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This is a partial snapshot — full model is in ErpDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
