using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Erp.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedPermissionCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Global ABAC permission catalog (ADR-0018 #42c). Resource:Action pairs are
            // designed in Erp.Application/Common/Attributes/RequirePermissionAttribute.cs —
            // keep both in sync. RolePermission grants for each company's Admin/Manager/
            // Contable roles are seeded per-company by SeedDefaultRolePermissionsHandler
            // (INotificationHandler<CompanyCreatedEvent>), not here, because RolePermission.
            // RoleId has a real FK to a specific tenant's Role row (no global row to point at).
            migrationBuilder.Sql(@"
INSERT INTO ""Permissions"" (""Id"", ""Code"", ""Description"", ""Resource"", ""Action"")
VALUES
    (gen_random_uuid(), 'Accounting:Close', 'Close Accounting', 'Accounting', 'Close'),
    (gen_random_uuid(), 'Accounting:Export', 'Export Accounting', 'Accounting', 'Export'),
    (gen_random_uuid(), 'Accounting:ManualEntry', 'ManualEntry Accounting', 'Accounting', 'ManualEntry'),
    (gen_random_uuid(), 'Accounting:Read', 'Read Accounting', 'Accounting', 'Read'),
    (gen_random_uuid(), 'Alert:Create', 'Create Alert', 'Alert', 'Create'),
    (gen_random_uuid(), 'Alert:Delete', 'Delete Alert', 'Alert', 'Delete'),
    (gen_random_uuid(), 'Alert:Manage', 'Manage Alert', 'Alert', 'Manage'),
    (gen_random_uuid(), 'Alert:Read', 'Read Alert', 'Alert', 'Read'),
    (gen_random_uuid(), 'Alert:Update', 'Update Alert', 'Alert', 'Update'),
    (gen_random_uuid(), 'BankAccount:Create', 'Create BankAccount', 'BankAccount', 'Create'),
    (gen_random_uuid(), 'BankAccount:Manage', 'Manage BankAccount', 'BankAccount', 'Manage'),
    (gen_random_uuid(), 'BankAccount:Read', 'Read BankAccount', 'BankAccount', 'Read'),
    (gen_random_uuid(), 'Budget:Approve', 'Approve Budget', 'Budget', 'Approve'),
    (gen_random_uuid(), 'Budget:Create', 'Create Budget', 'Budget', 'Create'),
    (gen_random_uuid(), 'Budget:Manage', 'Manage Budget', 'Budget', 'Manage'),
    (gen_random_uuid(), 'Budget:Read', 'Read Budget', 'Budget', 'Read'),
    (gen_random_uuid(), 'Budget:Update', 'Update Budget', 'Budget', 'Update'),
    (gen_random_uuid(), 'CashSession:Create', 'Create CashSession', 'CashSession', 'Create'),
    (gen_random_uuid(), 'CashSession:Manage', 'Manage CashSession', 'CashSession', 'Manage'),
    (gen_random_uuid(), 'CashSession:Read', 'Read CashSession', 'CashSession', 'Read'),
    (gen_random_uuid(), 'Client:Anonymize', 'Anonymize Client', 'Client', 'Anonymize'),
    (gen_random_uuid(), 'Client:Create', 'Create Client', 'Client', 'Create'),
    (gen_random_uuid(), 'Client:Delete', 'Delete Client', 'Client', 'Delete'),
    (gen_random_uuid(), 'Client:Read', 'Read Client', 'Client', 'Read'),
    (gen_random_uuid(), 'Client:Update', 'Update Client', 'Client', 'Update'),
    (gen_random_uuid(), 'Consolidation:Create', 'Create Consolidation', 'Consolidation', 'Create'),
    (gen_random_uuid(), 'Consolidation:Manage', 'Manage Consolidation', 'Consolidation', 'Manage'),
    (gen_random_uuid(), 'Consolidation:Read', 'Read Consolidation', 'Consolidation', 'Read'),
    (gen_random_uuid(), 'Contact:Anonymize', 'Anonymize Contact', 'Contact', 'Anonymize'),
    (gen_random_uuid(), 'Contact:Create', 'Create Contact', 'Contact', 'Create'),
    (gen_random_uuid(), 'Contact:Delete', 'Delete Contact', 'Contact', 'Delete'),
    (gen_random_uuid(), 'Contact:Read', 'Read Contact', 'Contact', 'Read'),
    (gen_random_uuid(), 'Contact:Update', 'Update Contact', 'Contact', 'Update'),
    (gen_random_uuid(), 'ContractedService:Create', 'Create ContractedService', 'ContractedService', 'Create'),
    (gen_random_uuid(), 'ContractedService:Delete', 'Delete ContractedService', 'ContractedService', 'Delete'),
    (gen_random_uuid(), 'ContractedService:Read', 'Read ContractedService', 'ContractedService', 'Read'),
    (gen_random_uuid(), 'CostCenter:Create', 'Create CostCenter', 'CostCenter', 'Create'),
    (gen_random_uuid(), 'CostCenter:Delete', 'Delete CostCenter', 'CostCenter', 'Delete'),
    (gen_random_uuid(), 'CostCenter:Read', 'Read CostCenter', 'CostCenter', 'Read'),
    (gen_random_uuid(), 'CostCenter:Update', 'Update CostCenter', 'CostCenter', 'Update'),
    (gen_random_uuid(), 'Currency:Create', 'Create Currency', 'Currency', 'Create'),
    (gen_random_uuid(), 'Currency:Delete', 'Delete Currency', 'Currency', 'Delete'),
    (gen_random_uuid(), 'Currency:Manage', 'Manage Currency', 'Currency', 'Manage'),
    (gen_random_uuid(), 'Currency:Read', 'Read Currency', 'Currency', 'Read'),
    (gen_random_uuid(), 'Currency:Update', 'Update Currency', 'Currency', 'Update'),
    (gen_random_uuid(), 'CustomerInvoice:Create', 'Create CustomerInvoice', 'CustomerInvoice', 'Create'),
    (gen_random_uuid(), 'CustomerInvoice:Read', 'Read CustomerInvoice', 'CustomerInvoice', 'Read'),
    (gen_random_uuid(), 'DeferredEntry:Create', 'Create DeferredEntry', 'DeferredEntry', 'Create'),
    (gen_random_uuid(), 'DeferredEntry:Manage', 'Manage DeferredEntry', 'DeferredEntry', 'Manage'),
    (gen_random_uuid(), 'DeferredEntry:Read', 'Read DeferredEntry', 'DeferredEntry', 'Read'),
    (gen_random_uuid(), 'Delivery:Create', 'Create Delivery', 'Delivery', 'Create'),
    (gen_random_uuid(), 'Delivery:Read', 'Read Delivery', 'Delivery', 'Read'),
    (gen_random_uuid(), 'Employee:Create', 'Create Employee', 'Employee', 'Create'),
    (gen_random_uuid(), 'Employee:Read', 'Read Employee', 'Employee', 'Read'),
    (gen_random_uuid(), 'Expense:Approve', 'Approve Expense', 'Expense', 'Approve'),
    (gen_random_uuid(), 'Expense:Create', 'Create Expense', 'Expense', 'Create'),
    (gen_random_uuid(), 'Expense:Delete', 'Delete Expense', 'Expense', 'Delete'),
    (gen_random_uuid(), 'Expense:Manage', 'Manage Expense', 'Expense', 'Manage'),
    (gen_random_uuid(), 'Expense:Read', 'Read Expense', 'Expense', 'Read'),
    (gen_random_uuid(), 'Expense:Update', 'Update Expense', 'Expense', 'Update'),
    (gen_random_uuid(), 'FacturaE:Export', 'Export FacturaE', 'FacturaE', 'Export'),
    (gen_random_uuid(), 'FacturaE:Manage', 'Manage FacturaE', 'FacturaE', 'Manage'),
    (gen_random_uuid(), 'FacturaE:Read', 'Read FacturaE', 'FacturaE', 'Read'),
    (gen_random_uuid(), 'FinancialStatement:Read', 'Read FinancialStatement', 'FinancialStatement', 'Read'),
    (gen_random_uuid(), 'Financing:Create', 'Create Financing', 'Financing', 'Create'),
    (gen_random_uuid(), 'Financing:Manage', 'Manage Financing', 'Financing', 'Manage'),
    (gen_random_uuid(), 'Financing:Read', 'Read Financing', 'Financing', 'Read'),
    (gen_random_uuid(), 'FixedAsset:Create', 'Create FixedAsset', 'FixedAsset', 'Create'),
    (gen_random_uuid(), 'FixedAsset:Manage', 'Manage FixedAsset', 'FixedAsset', 'Manage'),
    (gen_random_uuid(), 'FixedAsset:Read', 'Read FixedAsset', 'FixedAsset', 'Read'),
    (gen_random_uuid(), 'FixedAsset:Update', 'Update FixedAsset', 'FixedAsset', 'Update'),
    (gen_random_uuid(), 'Guarantee:Create', 'Create Guarantee', 'Guarantee', 'Create'),
    (gen_random_uuid(), 'Guarantee:Manage', 'Manage Guarantee', 'Guarantee', 'Manage'),
    (gen_random_uuid(), 'Guarantee:Read', 'Read Guarantee', 'Guarantee', 'Read'),
    (gen_random_uuid(), 'Inventory:Read', 'Read Inventory', 'Inventory', 'Read'),
    (gen_random_uuid(), 'Inventory:Write', 'Write Inventory', 'Inventory', 'Write'),
    (gen_random_uuid(), 'Invoice:Approve', 'Approve Invoice', 'Invoice', 'Approve'),
    (gen_random_uuid(), 'Invoice:Create', 'Create Invoice', 'Invoice', 'Create'),
    (gen_random_uuid(), 'Invoice:Delete', 'Delete Invoice', 'Invoice', 'Delete'),
    (gen_random_uuid(), 'Invoice:Export', 'Export Invoice', 'Invoice', 'Export'),
    (gen_random_uuid(), 'Invoice:Lock', 'Lock Invoice', 'Invoice', 'Lock'),
    (gen_random_uuid(), 'Invoice:Manage', 'Manage Invoice', 'Invoice', 'Manage'),
    (gen_random_uuid(), 'Invoice:Read', 'Read Invoice', 'Invoice', 'Read'),
    (gen_random_uuid(), 'Invoice:Update', 'Update Invoice', 'Invoice', 'Update'),
    (gen_random_uuid(), 'Lead:Convert', 'Convert Lead', 'Lead', 'Convert'),
    (gen_random_uuid(), 'Lead:Create', 'Create Lead', 'Lead', 'Create'),
    (gen_random_uuid(), 'Lead:Delete', 'Delete Lead', 'Lead', 'Delete'),
    (gen_random_uuid(), 'Lead:Read', 'Read Lead', 'Lead', 'Read'),
    (gen_random_uuid(), 'Lead:Update', 'Update Lead', 'Lead', 'Update'),
    (gen_random_uuid(), 'Lot:Create', 'Create Lot', 'Lot', 'Create'),
    (gen_random_uuid(), 'Lot:Delete', 'Delete Lot', 'Lot', 'Delete'),
    (gen_random_uuid(), 'Lot:Read', 'Read Lot', 'Lot', 'Read'),
    (gen_random_uuid(), 'Lot:Update', 'Update Lot', 'Lot', 'Update'),
    (gen_random_uuid(), 'Note:Create', 'Create Note', 'Note', 'Create'),
    (gen_random_uuid(), 'Note:Delete', 'Delete Note', 'Note', 'Delete'),
    (gen_random_uuid(), 'Note:Read', 'Read Note', 'Note', 'Read'),
    (gen_random_uuid(), 'Note:Update', 'Update Note', 'Note', 'Update'),
    (gen_random_uuid(), 'Product:Create', 'Create Product', 'Product', 'Create'),
    (gen_random_uuid(), 'Product:Manage', 'Manage Product', 'Product', 'Manage'),
    (gen_random_uuid(), 'Product:Read', 'Read Product', 'Product', 'Read'),
    (gen_random_uuid(), 'Product:Update', 'Update Product', 'Product', 'Update'),
    (gen_random_uuid(), 'Prorrata:Manage', 'Manage Prorrata', 'Prorrata', 'Manage'),
    (gen_random_uuid(), 'Prorrata:Read', 'Read Prorrata', 'Prorrata', 'Read'),
    (gen_random_uuid(), 'Provision:Create', 'Create Provision', 'Provision', 'Create'),
    (gen_random_uuid(), 'Provision:Delete', 'Delete Provision', 'Provision', 'Delete'),
    (gen_random_uuid(), 'Provision:Manage', 'Manage Provision', 'Provision', 'Manage'),
    (gen_random_uuid(), 'Provision:Read', 'Read Provision', 'Provision', 'Read'),
    (gen_random_uuid(), 'Provision:Update', 'Update Provision', 'Provision', 'Update'),
    (gen_random_uuid(), 'PurchaseInvoice:Create', 'Create PurchaseInvoice', 'PurchaseInvoice', 'Create'),
    (gen_random_uuid(), 'PurchaseInvoice:Read', 'Read PurchaseInvoice', 'PurchaseInvoice', 'Read'),
    (gen_random_uuid(), 'PurchaseOrder:Create', 'Create PurchaseOrder', 'PurchaseOrder', 'Create'),
    (gen_random_uuid(), 'PurchaseOrder:Delete', 'Delete PurchaseOrder', 'PurchaseOrder', 'Delete'),
    (gen_random_uuid(), 'PurchaseOrder:Read', 'Read PurchaseOrder', 'PurchaseOrder', 'Read'),
    (gen_random_uuid(), 'PurchaseOrder:Update', 'Update PurchaseOrder', 'PurchaseOrder', 'Update'),
    (gen_random_uuid(), 'Quote:Approve', 'Approve Quote', 'Quote', 'Approve'),
    (gen_random_uuid(), 'Quote:Create', 'Create Quote', 'Quote', 'Create'),
    (gen_random_uuid(), 'Quote:Delete', 'Delete Quote', 'Quote', 'Delete'),
    (gen_random_uuid(), 'Quote:Export', 'Export Quote', 'Quote', 'Export'),
    (gen_random_uuid(), 'Quote:Manage', 'Manage Quote', 'Quote', 'Manage'),
    (gen_random_uuid(), 'Quote:Read', 'Read Quote', 'Quote', 'Read'),
    (gen_random_uuid(), 'Quote:Update', 'Update Quote', 'Quote', 'Update'),
    (gen_random_uuid(), 'Recargo:Create', 'Create Recargo', 'Recargo', 'Create'),
    (gen_random_uuid(), 'Recargo:Manage', 'Manage Recargo', 'Recargo', 'Manage'),
    (gen_random_uuid(), 'Recargo:Read', 'Read Recargo', 'Recargo', 'Read'),
    (gen_random_uuid(), 'Receipt:Create', 'Create Receipt', 'Receipt', 'Create'),
    (gen_random_uuid(), 'Receipt:Read', 'Read Receipt', 'Receipt', 'Read'),
    (gen_random_uuid(), 'Report:Export', 'Export Report', 'Report', 'Export'),
    (gen_random_uuid(), 'SalesOrder:Create', 'Create SalesOrder', 'SalesOrder', 'Create'),
    (gen_random_uuid(), 'SalesOrder:Read', 'Read SalesOrder', 'SalesOrder', 'Read'),
    (gen_random_uuid(), 'Serial:Create', 'Create Serial', 'Serial', 'Create'),
    (gen_random_uuid(), 'Serial:Delete', 'Delete Serial', 'Serial', 'Delete'),
    (gen_random_uuid(), 'Serial:Read', 'Read Serial', 'Serial', 'Read'),
    (gen_random_uuid(), 'Serial:Update', 'Update Serial', 'Serial', 'Update'),
    (gen_random_uuid(), 'ServiceCatalog:Create', 'Create ServiceCatalog', 'ServiceCatalog', 'Create'),
    (gen_random_uuid(), 'ServiceCatalog:Read', 'Read ServiceCatalog', 'ServiceCatalog', 'Read'),
    (gen_random_uuid(), 'ServiceCatalog:Update', 'Update ServiceCatalog', 'ServiceCatalog', 'Update'),
    (gen_random_uuid(), 'Settlement:Create', 'Create Settlement', 'Settlement', 'Create'),
    (gen_random_uuid(), 'Settlement:Export', 'Export Settlement', 'Settlement', 'Export'),
    (gen_random_uuid(), 'Settlement:Manage', 'Manage Settlement', 'Settlement', 'Manage'),
    (gen_random_uuid(), 'Settlement:Read', 'Read Settlement', 'Settlement', 'Read'),
    (gen_random_uuid(), 'Stock:Manage', 'Manage Stock', 'Stock', 'Manage'),
    (gen_random_uuid(), 'Stock:Read', 'Read Stock', 'Stock', 'Read'),
    (gen_random_uuid(), 'Supplier:Anonymize', 'Anonymize Supplier', 'Supplier', 'Anonymize'),
    (gen_random_uuid(), 'Supplier:Create', 'Create Supplier', 'Supplier', 'Create'),
    (gen_random_uuid(), 'Supplier:Read', 'Read Supplier', 'Supplier', 'Read'),
    (gen_random_uuid(), 'Supplier:Update', 'Update Supplier', 'Supplier', 'Update'),
    (gen_random_uuid(), 'UserManagement:Delete', 'Delete UserManagement', 'UserManagement', 'Delete'),
    (gen_random_uuid(), 'UserManagement:Read', 'Read UserManagement', 'UserManagement', 'Read'),
    (gen_random_uuid(), 'UserManagement:Write', 'Write UserManagement', 'UserManagement', 'Write'),
    (gen_random_uuid(), 'Valuation:Read', 'Read Valuation', 'Valuation', 'Read'),
    (gen_random_uuid(), 'Vat:Manage', 'Manage Vat', 'Vat', 'Manage'),
    (gen_random_uuid(), 'Vat:Read', 'Read Vat', 'Vat', 'Read'),
    (gen_random_uuid(), 'Vies:Manage', 'Manage Vies', 'Vies', 'Manage'),
    (gen_random_uuid(), 'Vies:Read', 'Read Vies', 'Vies', 'Read'),
    (gen_random_uuid(), 'Warehouse:Create', 'Create Warehouse', 'Warehouse', 'Create'),
    (gen_random_uuid(), 'Warehouse:Manage', 'Manage Warehouse', 'Warehouse', 'Manage'),
    (gen_random_uuid(), 'Warehouse:Read', 'Read Warehouse', 'Warehouse', 'Read'),
    (gen_random_uuid(), 'Warehouse:Update', 'Update Warehouse', 'Warehouse', 'Update');
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DELETE FROM ""Permissions"" WHERE ""Code"" LIKE '%:%';");
        }
    }
}
