// <auto-generated />
// NOTE: timestamp conflict resolved — AddOcrConfidence uses ID 20260321030001
// (file keeps original name for git history; Migration ID is what EF Core uses)
using Erp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Erp.Infrastructure.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20260321030001_AddOcrConfidence")]
    partial class AddOcrConfidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
