<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Erp.Application\Erp.Application.csproj" />
    <ProjectReference Include="..\..\Accounting\Application\Erp.Modules.Accounting.Application.csproj" />
    <ProjectReference Include="..\Domain\Erp.Modules.Payroll.Domain.csproj" />
  </ItemGroup>
</Project>
