using Erp.Domain.Common;

namespace Erp.Domain.Entities.Core;

/// <summary>
/// Evento del calendario fiscal español.
/// Cada evento representa una obligación tributaria con su fecha límite de presentación.
///
/// Modelos soportados:
///   303 — IVA trimestral
///   390 — Resumen anual IVA
///   347 — Operaciones con terceros (febrero)
///   349 — Intracomunitarias (mensual/trimestral)
///   111 — Retenciones IRPF trimestral
///   190 — Resumen anual retenciones
///   130 — Pago fraccionado Impuesto Sociedades (abril, octubre, diciembre)
///   100 — Impuesto Sociedades (25/30 julio)
///   180 — Arrendamientos (febrero)
/// </summary>
public class FiscalEvent : AuditableEntity
{
    public Guid CompanyId { get; set; }

    /// <summary>Código oficial del modelo AEAT: "303", "347", "349", "390", "111", "190", "130", "100", "180"</summary>
    public string ModelCode { get; set; } = string.Empty;

    /// <summary>Nombre descriptivo del modelo</summary>
    public string ModelName { get; set; } = string.Empty;

    /// <summary>Año fiscal al que corresponde el evento</summary>
    public int Year { get; set; }

    /// <summary>Trimestre (1-4). Null si es mensual o anual.</summary>
    public int? Quarter { get; set; }

    /// <summary>Mes (1-12). Null si es trimestral o anual.</summary>
    public int? Month { get; set; }

    /// <summary>Fecha límite de presentación (art. 19 LGT: día 20 del mes siguiente)</summary>
    public DateTime DeadlineDate { get; set; }

    /// <summary>Fecha en que se envía recordatorio (7 días antes del deadline)</summary>
    public DateTime ReminderDate { get; set; }

    /// <summary>Último día para domiciliar el pago (Modelos con pago obligatorio)</summary>
    public DateTime? PaymentDeadlineDate { get; set; }

    /// <summary>Estado: Pending | Reminded | InProgress | Submitted | Paid | Missed</summary>
    public string Status { get; set; } = "Pending";

    /// <summary>Fecha en que se marcó como Submitted</summary>
    public DateTime? SubmittedAt { get; set; }

    /// <summary>Número de referencia del modelo presentado (ej. NRGP del SII)</summary>
    public string? SubmissionReference { get; set; }

    /// <summary>Importe a ingresar (si se conoce de antemano)</summary>
    public decimal? Amount { get; set; }

    /// <summary>Notas u observaciones del usuario</summary>
    public string? Notes { get; set; }

    /// <summary>Indica si el evento se generó automáticamente para el año</summary>
    public bool IsAutoGenerated { get; set; }
}
