// <auto-generated />
using System;
using Erp.Modules.Expenses.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp.Modules.Expenses.Infrastructure.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260331143436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("expenses")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.AccountingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCredit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountDebit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExpenseDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseDocumentId");

                    b.ToTable("AccountingEntries", "expenses");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountingEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExpenseUploadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExpenseUploadId1")
                        .HasColumnType("uuid");

                    b.Property<string>("HashSignature")
                        .HasColumnType("text");

                    b.Property<decimal?>("IRPFAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IRPFRate")
                        .HasColumnType("numeric");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("OcrConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("OcrRawData")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierName")
                        .HasColumnType("text");

                    b.Property<string>("SupplierTaxId")
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxBase")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VATAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VATRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpenseUploadId1");

                    b.ToTable("ExpenseDocuments", "expenses");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ExpenseDocumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VATRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseDocumentId")
                        .HasDatabaseName("IX_ExpenseDocumentLines_DocumentId");

                    b.ToTable("ExpenseDocumentLines", "expenses");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExpenseDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicTokenUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExpenseDocumentId");

                    b.ToTable("ExpenseUploads", "expenses");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.AccountingEntry", b =>
                {
                    b.HasOne("Erp.Modules.Expenses.Domain.Entities.ExpenseDocument", "ExpenseDocument")
                        .WithMany()
                        .HasForeignKey("ExpenseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseDocument");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseDocument", b =>
                {
                    b.HasOne("Erp.Modules.Expenses.Domain.Entities.ExpenseUpload", "ExpenseUpload")
                        .WithMany()
                        .HasForeignKey("ExpenseUploadId1");

                    b.Navigation("ExpenseUpload");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseDocumentLine", b =>
                {
                    b.HasOne("Erp.Modules.Expenses.Domain.Entities.ExpenseDocument", "ExpenseDocument")
                        .WithMany("Lines")
                        .HasForeignKey("ExpenseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseDocument");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseUpload", b =>
                {
                    b.HasOne("Erp.Modules.Expenses.Domain.Entities.ExpenseDocument", "ExpenseDocument")
                        .WithMany()
                        .HasForeignKey("ExpenseDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExpenseDocument");
                });

            modelBuilder.Entity("Erp.Modules.Expenses.Domain.Entities.ExpenseDocument", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
